defaults:
  - train
  - _self_

batch_size: 10000

mesh:
  _target_: pinnstorch.data.PointCloud
  root_dir: ${paths.data_dir}
  read_data_fn: ???

train_datasets:
  - mesh_sampler:
      _target_: pinnstorch.data.MeshSampler
      _partial_: true
      solution:
        - c

  - mesh_sampler:
      _target_: pinnstorch.data.MeshSampler
      _partial_: true
      collection_points:
        - e1
        - e2
        - e3
        - e4
        - e5
      use_lhs: false

val_dataset:
  - mesh_sampler:
      _target_: pinnstorch.data.MeshSampler
      _partial_: true
      solution:
        - c
        - u
        - v
        - w
        - p

pred_dataset:
  - mesh_sampler:
      _target_: pinnstorch.data.MeshSampler
      _partial_: true
      idx_t: 100
      solution:
        - c
        - u
        - v
        - w
        - p

test_dataset:
  - mesh_sampler:
      _target_: pinnstorch.data.MeshSampler
      _partial_: true
      idx_t: 100
      solution:
        - c
        - u
        - v
        - w
        - p

net:
  _target_: pinnstorch.models.NetHFM
  layers: [4, 250, 250, 250, 250, 250, 250, 250, 250, 250, 250, 5]
  output_names:
    - c
    - u
    - v
    - w
    - p

model:
  loss_fn: mse

trainer:
  accelerator: gpu
  max_epochs: 1
  max_steps: 500
  devices: [0]
  deterministic: false
  check_val_every_n_epoch: 10

train: true
val: true
test: false
save_pred: true 

optimized_metric:
  error:
    - c
    - u
    - v
    - w

task_name: aneurysm3D

hydra:
  searchpath:
    - pkg://pinnstorch/conf
